openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /interrogate/:
    get:
      operationId: interrogate_retrieve
      description: Restituisce la lista degli LLM disponibili
      tags:
      - interrogate
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LLMResponse'
          description: ''
    post:
      operationId: interrogate_create
      description: Interroga un LLM specifico con un prompt
      tags:
      - interrogate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LLMRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LLMRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LLMRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LLMResponse'
          description: ''
components:
  schemas:
    LLMRequest:
      type: object
      properties:
        llm_name:
          type: string
        prompt:
          type: string
      required:
      - llm_name
      - prompt
    LLMResponse:
      type: object
      properties:
        llm_name:
          type: string
        prompt:
          type: string
        answer:
          type: string
      required:
      - answer
      - llm_name
      - prompt
