name: Lint and test backend

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.3"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.13.3'
            cache: 'pip'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format code with black
        run: |
          black ./server/ArtificialQI/

      - name: Analysing the code with pylint
        run: |
          pylint --load-plugins pylint_django \
          --fail-under=9 \
          --disable=import-error,broad-except \
          --ignore=tests \
          ./server/ArtificialQI/

      - name: Run tests with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/server
        run: |
          pytest ./server/ArtificialQI
          pytest ./microservices/LLMService
